[custom]
# --- 规则集设定 ---
ruleset=🎯 无墙直连,https://github.com/Snailmad/DocumentLibrary/raw/refs/heads/main/OpenClash/rule/Direct.list
ruleset=🎮 steam游戏,https://github.com/Snailmad/DocumentLibrary/raw/refs/heads/main/OpenClash/rule/steam.list
ruleset=🚀 爬墙代理,https://github.com/Snailmad/DocumentLibrary/raw/refs/heads/main/OpenClash/rule/ProxyLite.list
ruleset=🎯 无墙直连,[]GEOSITE,CN
ruleset=🚀 爬墙代理,[]GEOSITE,geolocation-!cn
ruleset=🎯 无墙直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL

# --- 顶层策略组 (业务入口) ---
# 将各地区的“自动”组放入入口，方便一键切换到该地区的最佳节点
custom_proxy_group=🎯 无墙直连`select`[]DIRECT`[]🐸 手动切换`[]🇭🇰 香港自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动`[]🇹🇼 台湾自动`[]🌐 全部自动
custom_proxy_group=🎮 steam游戏`select`[]🐸 手动切换`[]🇭🇰 香港自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动`[]🇹🇼 台湾自动`[]🌐 全部自动`[]DIRECT
custom_proxy_group=🚀 爬墙代理`select`[]🐸 手动切换`[]🇭🇰 香港自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动`[]🇹🇼 台湾自动`[]🌐 全部自动`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🐸 手动切换`[]🇭🇰 香港自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动`[]🇹🇼 台湾自动`[]🌐 全部自动

# --- 自动策略组 (url-test 模式) ---
# 语法说明：组名`url-test`正则表达式`测试地址`测试间隔(秒)
# 这里的 60 代表每 60 秒自动扫描一次，并切换到延迟最低的节点
custom_proxy_group=🇭🇰 香港自动`url-test`.*(香港|HK|Hong Kong|🇭🇰|HongKong)`http://www.gstatic.com/generate_204`60
custom_proxy_group=🇯🇵 日本自动`url-test`.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)`http://www.gstatic.com/generate_204`60
custom_proxy_group=🇸🇬 新加坡自动`url-test`.*(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`60
custom_proxy_group=🇹🇼 台湾自动`url-test`.*(台湾|台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`60
custom_proxy_group=🌐 全部自动`url-test`^.*`http://www.gstatic.com/generate_204`60

# --- 手动策略组 (select 模式) ---
# 用于在自动失效或有特殊需求时，手动指定某个特定的节点
custom_proxy_group=🐸 手动切换`select`.*

enable_rule_generator=true
overwrite_original_rules=true
overwrite_original_rules=true
